[[DGGRID7_jll]]
deps = [ "Artifacts", "GDAL_jll", "JLLWrappers", "Libdl", "Pkg",]
uuid = "56fc471b-e449-5679-a438-44d065b4fb79"

[[GDAL]]
deps = [ "CEnum", "GDAL_jll", "MozillaCACerts_jll", "PROJ_jll",]
uuid = "add2ef01-049f-52c4-9ee2-e494f65e021a"

[[GDAL_jll]]
deps = [ "Artifacts", "Expat_jll", "GEOS_jll", "JLLWrappers", "LibCURL_jll", "LibSSH2_jll", "Libdl", "Libtiff_jll", "MbedTLS_jll", "OpenJpeg_jll", "PROJ_jll", "Pkg", "SQLite_jll", "Zlib_jll", "Zstd_jll", "libgeotiff_jll", "nghttp2_jll",]
uuid = "a7073274-a066-55f0-b90d-d619367d196c"

[[LibGEOS]]
deps = [ "CEnum", "GEOS_jll", "GeoInterface",]
uuid = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"

[[Proj4]]
deps = [ "CEnum", "PROJ_jll",]
uuid = "9a7e659c-8ee8-5706-894e-f68f43bc57ea"

[[CEnum]]
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[[JLLWrappers]]
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"

[[libgeotiff_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Libtiff_jll", "PROJ_jll", "Pkg",]
uuid = "06c338fa-64ff-565b-ac2f-249532af990e"

[[MozillaCACerts_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[Zlib_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[Zstd_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"

[[LibSSH2_jll]]
deps = [ "Libdl", "MbedTLS_jll", "Pkg",]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[SQLite_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll",]
uuid = "76ed43ae-9a5d-5a62-8c75-30186b810ce8"

[[OpenJpeg_jll]]
deps = [ "Libdl", "Libtiff_jll", "LittleCMS_jll", "Pkg", "libpng_jll",]
uuid = "643b3616-a352-519d-856d-80112ee9badc"

[[Expat_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"

[[Artifacts]]
deps = [ "Pkg",]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[nghttp2_jll]]
deps = [ "Libdl", "Pkg",]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[GEOS_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "d604d12d-fa86-5845-992e-78dc15976526"

[[MbedTLS_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[Libtiff_jll]]
deps = [ "Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll",]
uuid = "89763e89-9b03-5906-acba-b20f662cd828"

[[PROJ_jll]]
deps = [ "Artifacts", "JLLWrappers", "LibCURL_jll", "LibSSH2_jll", "Libdl", "Libtiff_jll", "MbedTLS_jll", "Pkg", "SQLite_jll", "Zlib_jll", "nghttp2_jll",]
uuid = "58948b4f-47e0-5654-a9ad-f609743f8632"

[[GeoInterface]]
deps = [ "RecipesBase", "Test",]
uuid = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[[LibCURL_jll]]
deps = [ "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Pkg", "Zlib_jll", "nghttp2_jll",]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[LittleCMS_jll]]
deps = [ "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg",]
uuid = "d3a379c0-f9a3-5b72-a4c0-6bf4d2e8af0f"

[[libpng_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll",]
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"

[[JpegTurbo_jll]]
deps = [ "Artifacts", "JLLWrappers", "Libdl", "Pkg",]
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"

[[RecipesBase]]
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

